.PHONY: fmt checkov install lint test fmt-ci
fmt:
	terraform fmt -recursive aws &&\
	terragrunt hclfmt

checkov:
	checkov --directory=aws

build: ;

install: ;

install-dev: ;

lint: ;

test: ;

fmt-ci: ;