"""identify dynamic scans

Revision ID: 90fbbca6884e
Revises: ff660f256a86
Create Date: 2021-11-08 15:17:49.286994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fbbca6884e'
down_revision = 'ff660f256a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_types', sa.Column('dynamic', sa.Boolean(), nullable=True))
    op.execute("UPDATE scan_types SET dynamic = false;")
    op.execute("UPDATE scan_types SET dynamic = true WHERE name = 'Nuclei';")
    op.execute("UPDATE scan_types SET dynamic = true WHERE name = 'OWASP Zap';")
    op.alter_column('scan_types', 'dynamic', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_types', 'dynamic')
    # ### end Alembic commands ###
