"""ignore tweaks

Revision ID: b77929e07997
Revises: 09b1dec8eb5d
Create Date: 2021-10-25 19:52:19.991561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b77929e07997"
down_revision = "09b1dec8eb5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scan_ignores", sa.Column("location", sa.String(), nullable=False))
    op.add_column("scan_ignores", sa.Column("condition", sa.String(), nullable=False))
    op.drop_column("scan_ignores", "ignore_condition")
    # ### end Alembic commands ###


def downgrade():
    op.execute(
        """
        DELETE FROM scan_ignores;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scan_ignores",
        sa.Column(
            "ignore_condition", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("scan_ignores", "condition")
    op.drop_column("scan_ignores", "location")
    # ### end Alembic commands ###
