name: Build containers CI

on:
  workflow_dispatch:
  pull_request:

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ca-central-1.amazonaws.com/scan-websites

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api: 'api/**'
            scanners/axe-core: 'scanners/axe-core/**'
            scanners/github: 'scanners/github/**'
            runners/owasp-zap: 'runners/owasp-zap/**'
            runners/nuclei: 'runners/nuclei/**'

  build:
    if: needs.changes.outputs.images != '[]'
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.images) }}

    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2 # tag=v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Retrieve AWS Distro for OpenTelemetry Lambda layer
        if: matrix.image == 'api'
        working-directory: ./${{ matrix.image }}
        run: |
          aws lambda get-layer-version-by-arn \
          --region ca-central-1 \
          --arn arn:aws:lambda:ca-central-1:901920570463:layer:aws-otel-python38-ver-1-7-1:1 \
          | jq -r '.Content.Location' \
          | xargs curl -o otel-layer.zip

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@3d4e073ce6a6845ed27b30a0fe05b6e22c80ac6b # tag=v1
        
      - name: Build container
        working-directory: ./${{ matrix.image }}
        run: |
          docker build \
          --build-arg git_sha=$GITHUB_SHA \
          -t $REGISTRY/${{ matrix.image }}:latest .

      - name: Generate ${{ matrix.image }}/docker SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@b09c1aefae9876dd2a23888c50b2daaa137ba01d # pin@b09c1aefae9876dd2a23888c50b2daaa137ba01d # tag=v1
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          docker_image: $REGISTRY/${{ matrix.image }}:latest
          project_name: scan-websites/${{ matrix.image }}/docker
          project_type: docker          
