name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**
      - scanners/axe-core/**
      - scanners/owasp-zap/**

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scan-websites
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
          folder: ["api", "scanners/axe-core", "scanners/owasp-zap"] 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dev dependencies
        working-directory: ${{ matrix.folder }}
        run: make install-dev

      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: make install

      - name: Lint
        working-directory: ${{ matrix.folder }}
        run: make lint-ci

      - name: Format
        working-directory: ${{ matrix.folder }}
        run: make fmt-ci

      - name: Test
        working-directory: ${{ matrix.folder }}
        env:
          SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@127.0.0.1/scan-websites
          SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:postgres@127.0.0.1/scan-websites
        run: make test
