name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**
      - scanners/axe-core/**
      - scanners/github/**
      - terragrunt/**
      - .github/workflows/ci_code.yml

env:
  TERRAGRUNT_VERSION: v0.31.1

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scan-websites
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
          folder: ["api", "scanners/axe-core", "terragrunt"]

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Check for changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          filters: |
            changes:
              - '${{ matrix.folder }}/**'
              - '.github/workflows/ci_code.yml'

      - name: Setup python
        if: ${{ steps.filter.outputs.changes == 'true' }}
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.9"

      - name: Setup node
        if: ${{ steps.filter.outputs.changes == 'true' && matrix.folder != 'terragrunt' }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "14"

      - name: Setup Terragrunt
        if: ${{ steps.filter.outputs.changes == 'true' && matrix.folder == 'terragrunt' }}
        run: |
          mkdir -p bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/*
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install dev dependencies
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make install-dev

      - name: Install dependencies
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make install

      - name: Lint
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make lint-ci

      - name: Format
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        run: make fmt-ci

      - name: Test
        if: ${{ steps.filter.outputs.changes == 'true' }}
        working-directory: ${{ matrix.folder }}
        env:
          SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@127.0.0.1/scan-websites
          SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:postgres@127.0.0.1/scan-websites
        run: make test
