name: Shellscripts PR Workflow
on:
  pull_request:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: |
        .github/workflows/scripts/run-shellcheck.sh

  script_test:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: |
        .github/workflows/scripts/test_scripts.sh


