name: Shellscripts PR Workflow
on:
  pull_request:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - name: Shellcheck
      run: .github/workflows/scripts/run_shellcheck.sh

  script_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - name: Test Scripts
      run: .github/workflows/scripts/test_scripts.sh


