name: Shellscripts PR Workflow
on:
  pull_request:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - name: Shellcheck
      run: .github/workflows/scripts/run_shellcheck.sh

  script_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - name: Test Scripts
      run: .github/workflows/scripts/test_scripts.sh


