name: Shellscripts PR Workflow
on:
  pull_request:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Shellcheck
      run: .github/workflows/scripts/run_shellcheck.sh

  script_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Test Scripts
      run: .github/workflows/scripts/test_scripts.sh


