name: Shellscripts PR Workflow
on:
  pull_request:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Shellcheck
      run: .github/workflows/scripts/run_shellcheck.sh

  script_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Test Scripts
      run: .github/workflows/scripts/test_scripts.sh


